In [70]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [71]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [72]:
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [73]:
## encoding categorical variables
label_encoder = LabelEncoder()
data['Gender']= label_encoder.fit_transform(data['Gender'])

In [74]:
onehot_encoder = OneHotEncoder(sparse_output=False)

geo_encoded = onehot_encoder.fit_transform(data[['Geography']])

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder.get_feature_names_out(['Geography'])
)

geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [75]:
df=pd.concat([data, geo_encoded_df], axis=1).drop(['Geography'], axis=1)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [76]:
X=df.drop(['EstimatedSalary'], axis=1)
y=df['EstimatedSalary']

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [78]:
## make pickle files for the scaler and encoders
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)    

with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot_encoder, file)

In [84]:
## ANN Regression Model
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),   
    Dense(1, activation='linear')
])  

## compile the model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mean_squared_error',
    metrics=['mean_absolute_error']
)

In [85]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [86]:

import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [87]:
early_stopping = EarlyStopping(
    monitor='val_loss', 
    patience=10,
    restore_best_weights=True
)

In [88]:
model.fit(
    X_train_scaled,
    y_train,
    validation_split=0.2,
    epochs=100,
    callbacks=[early_stopping, tensorboard_callback]
)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 13309396992.0000 - mean_absolute_error: 99984.2578 - val_loss: 13700704256.0000 - val_mean_absolute_error: 102051.9609
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 13246898176.0000 - mean_absolute_error: 99672.2422 - val_loss: 13565070336.0000 - val_mean_absolute_error: 101390.1094
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13000569856.0000 - mean_absolute_error: 98439.0234 - val_loss: 13180295168.0000 - val_mean_absolute_error: 99517.4609
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12467850240.0000 - mean_absolute_error: 95782.9297 - val_loss: 12472033280.0000 - val_mean_absolute_error: 96057.1719
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11607623680.0000 - mean_absolute_error: 91508.7422 - val_loss: 11431656448.0000 - val_mean_absolute_error: 90966.3438
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10449309696.0000 - mean_absolute_error: 85760.0000 - val_loss: 10124780544.0000 - val_mean_absolute_error: 84478.6094
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9084759040.0000 - mean_absolute_error: 78953.0547 - val_loss: 8664942592.0000 - val_mean_absolute_error: 77130.7422
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7663787520.0000 - mean_absolute_error: 71788.2578 - val_loss: 7224117248.0000 - val_mean_absolute_error: 69775.1797
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6339845120.0000 - mean_absolute_error: 65068.6836 - val_loss: 5950856704.0000 - val_mean_absolute_error: 63226.7734
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5246883328.0000 - mean_absolute_error: 59463.1719 - val_loss: 4948652544.0000 - val_mean_absolute_error: 57971.4531
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4453404672.0000 - mean_absolute_error: 55406.7656 - val_loss: 4254199552.0000 - val_mean_absolute_error: 54320.3867
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3950582528.0000 - mean_absolute_error: 52822.1094 - val_loss: 3838324480.0000 - val_mean_absolute_error: 52054.1133
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3672278016.0000 - mean_absolute_error: 51416.9258 - val_loss: 3615815680.0000 - val_mean_absolute_error: 50863.3555
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3533943040.0000 - mean_absolute_error: 50729.7539 - val_loss: 3501803520.0000 - val_mean_absolute_error: 50311.1836
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3468334080.0000 - mean_absolute_error: 50424.0781 - val_loss: 3445074176.0000 - val_mean_absolute_error: 50044.4492
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3435074304.0000 - mean_absolute_error: 50269.8594 - val_loss: 3417058816.0000 - val_mean_absolute_error: 49907.3359
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3415646208.0000 - mean_absolute_error: 50177.9531 - val_loss: 3398923008.0000 - val_mean_absolute_error: 49816.9805
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3401761024.0000 - mean_absolute_error: 50114.8711 - val_loss: 3385564928.0000 - val_mean_absolute_error: 49754.5312
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3390479616.0000 - mean_absolute_error: 50053.4102 - val_loss: 3376059904.0000 - val_mean_absolute_error: 49708.8555
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3381419264.0000 - mean_absolute_error: 50008.4336 - val_loss: 3368155648.0000 - val_mean_absolute_error: 49673.4102
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3373265920.0000 - mean_absolute_error: 49958.6836 - val_loss: 3362289408.0000 - val_mean_absolute_error: 49650.7500
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3365856512.0000 - mean_absolute_error: 49923.4688 - val_loss: 3357065984.0000 - val_mean_absolute_error: 49629.8242
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3359778048.0000 - mean_absolute_error: 49886.7969 - val_loss: 3352136192.0000 - val_mean_absolute_error: 49609.1992
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3353980416.0000 - mean_absolute_error: 49853.7656 - val_loss: 3347387392.0000 - val_mean_absolute_error: 49589.1641
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3349157376.0000 - mean_absolute_error: 49828.5859 - val_loss: 3343422464.0000 - val_mean_absolute_error: 49571.1055
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3344828416.0000 - mean_absolute_error: 49801.1797 - val_loss: 3340513792.0000 - val_mean_absolute_error: 49560.4336
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3340610816.0000 - mean_absolute_error: 49775.9766 - val_loss: 3338258432.0000 - val_mean_absolute_error: 49552.2734
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3336796672.0000 - mean_absolute_error: 49758.3008 - val_loss: 3335820800.0000 - val_mean_absolute_error: 49543.3086
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3333859584.0000 - mean_absolute_error: 49740.3281 - val_loss: 3333366784.0000 - val_mean_absolute_error: 49533.9297
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3330694144.0000 - mean_absolute_error: 49716.3047 - val_loss: 3332285696.0000 - val_mean_absolute_error: 49531.5469
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3327830016.0000 - mean_absolute_error: 49703.7539 - val_loss: 3328448256.0000 - val_mean_absolute_error: 49518.1914
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3325268224.0000 - mean_absolute_error: 49689.3359 - val_loss: 3327839232.0000 - val_mean_absolute_error: 49518.5781
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3322724352.0000 - mean_absolute_error: 49672.2891 - val_loss: 3326300928.0000 - val_mean_absolute_error: 49513.5742
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 3320316672.0000 - mean_absolute_error: 49656.4531 - val_loss: 3324820736.0000 - val_mean_absolute_error: 49508.8086
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 3318211584.0000 - mean_absolute_error: 49641.5352 - val_loss: 3323645184.0000 - val_mean_absolute_error: 49504.7148
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 3316541440.0000 - mean_absolute_error: 49629.9062 - val_loss: 3322014720.0000 - val_mean_absolute_error: 49501.5547
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 3314835456.0000 - mean_absolute_error: 49621.3164 - val_loss: 3319769344.0000 - val_mean_absolute_error: 49494.9648
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 3313068288.0000 - mean_absolute_error: 49608.8398 - val_loss: 3320292864.0000 - val_mean_absolute_error: 49499.9336
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3311613952.0000 - mean_absolute_error: 49600.3047 - val_loss: 3319303680.0000 - val_mean_absolute_error: 49497.7031
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3309994240.0000 - mean_absolute_error: 49590.5781 - val_loss: 3320068096.0000 - val_mean_absolute_error: 49500.6250
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3308723456.0000 - mean_absolute_error: 49581.2305 - val_loss: 3318910464.0000 - val_mean_absolute_error: 49500.5742
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3307372544.0000 - mean_absolute_error: 49572.3516 - val_loss: 3317582848.0000 - val_mean_absolute_error: 49496.9062
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3306097920.0000 - mean_absolute_error: 49561.6016 - val_loss: 3317543936.0000 - val_mean_absolute_error: 49496.6953
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3305225216.0000 - mean_absolute_error: 49557.0938 - val_loss: 3316867328.0000 - val_mean_absolute_error: 49496.6953
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3304275200.0000 - mean_absolute_error: 49552.7734 - val_loss: 3316653824.0000 - val_mean_absolute_error: 49498.7695
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3303367680.0000 - mean_absolute_error: 49545.6250 - val_loss: 3315336704.0000 - val_mean_absolute_error: 49494.0117
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3302123008.0000 - mean_absolute_error: 49530.2031 - val_loss: 3315477504.0000 - val_mean_absolute_error: 49496.3750
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3301190144.0000 - mean_absolute_error: 49528.0547 - val_loss: 3315247616.0000 - val_mean_absolute_error: 49496.3867
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3300316672.0000 - mean_absolute_error: 49519.3633 - val_loss: 3314797056.0000 - val_mean_absolute_error: 49498.3008
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3299681536.0000 - mean_absolute_error: 49518.1602 - val_loss: 3314764800.0000 - val_mean_absolute_error: 49499.7891
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3299024128.0000 - mean_absolute_error: 49510.8047 - val_loss: 3314709248.0000 - val_mean_absolute_error: 49499.5898
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3297888512.0000 - mean_absolute_error: 49501.3164 - val_loss: 3314802432.0000 - val_mean_absolute_error: 49501.8867
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3297783040.0000 - mean_absolute_error: 49499.6953 - val_loss: 3313867264.0000 - val_mean_absolute_error: 49501.8555
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3296708096.0000 - mean_absolute_error: 49495.0586 - val_loss: 3313804288.0000 - val_mean_absolute_error: 49502.0742
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3295934208.0000 - mean_absolute_error: 49487.6250 - val_loss: 3313006592.0000 - val_mean_absolute_error: 49498.5703
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3295339264.0000 - mean_absolute_error: 49483.0586 - val_loss: 3313751808.0000 - val_mean_absolute_error: 49502.1562
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3294618880.0000 - mean_absolute_error: 49477.9141 - val_loss: 3313136384.0000 - val_mean_absolute_error: 49503.5391
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3293963776.0000 - mean_absolute_error: 49473.1992 - val_loss: 3314728960.0000 - val_mean_absolute_error: 49511.0352
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3293963264.0000 - mean_absolute_error: 49471.5000 - val_loss: 3313886464.0000 - val_mean_absolute_error: 49506.8594
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3293309952.0000 - mean_absolute_error: 49466.5000 - val_loss: 3313639168.0000 - val_mean_absolute_error: 49508.2539
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3292819200.0000 - mean_absolute_error: 49462.4453 - val_loss: 3313961984.0000 - val_mean_absolute_error: 49512.1602
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3292044032.0000 - mean_absolute_error: 49456.0664 - val_loss: 3313323008.0000 - val_mean_absolute_error: 49509.6367
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3291416064.0000 - mean_absolute_error: 49453.6602 - val_loss: 3313451264.0000 - val_mean_absolute_error: 49511.9805
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3291150848.0000 - mean_absolute_error: 49449.1289 - val_loss: 3312911872.0000 - val_mean_absolute_error: 49509.3789
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 3290614784.0000 - mean_absolute_error: 49445.3633 - val_loss: 3313356288.0000 - val_mean_absolute_error: 49513.3164
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3290263296.0000 - mean_absolute_error: 49444.7617 - val_loss: 3313013248.0000 - val_mean_absolute_error: 49511.9258
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3290020352.0000 - mean_absolute_error: 49440.6836 - val_loss: 3314090752.0000 - val_mean_absolute_error: 49517.1016
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3289713664.0000 - mean_absolute_error: 49440.0703 - val_loss: 3311840512.0000 - val_mean_absolute_error: 49510.6445
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3289161984.0000 - mean_absolute_error: 49430.3047 - val_loss: 3315008256.0000 - val_mean_absolute_error: 49521.4688
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3288521984.0000 - mean_absolute_error: 49432.3750 - val_loss: 3313980416.0000 - val_mean_absolute_error: 49517.4141
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3288192768.0000 - mean_absolute_error: 49428.0664 - val_loss: 3313306880.0000 - val_mean_absolute_error: 49517.0039
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3287658240.0000 - mean_absolute_error: 49423.8867 - val_loss: 3312903680.0000 - val_mean_absolute_error: 49518.2461
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3287181824.0000 - mean_absolute_error: 49423.2695 - val_loss: 3313025280.0000 - val_mean_absolute_error: 49514.6055
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3286830848.0000 - mean_absolute_error: 49416.6836 - val_loss: 3312903424.0000 - val_mean_absolute_error: 49518.4961
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3286330624.0000 - mean_absolute_error: 49413.7305 - val_loss: 3311309568.0000 - val_mean_absolute_error: 49517.4062
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3286415872.0000 - mean_absolute_error: 49414.0586 - val_loss: 3312388608.0000 - val_mean_absolute_error: 49518.3047
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3285956352.0000 - mean_absolute_error: 49407.7617 - val_loss: 3312287744.0000 - val_mean_absolute_error: 49516.0781
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 3285332224.0000 - mean_absolute_error: 49405.0898 - val_loss: 3312160512.0000 - val_mean_absolute_error: 49515.1836
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3284949760.0000 - mean_absolute_error: 49400.6797 - val_loss: 3312198912.0000 - val_mean_absolute_error: 49519.5664
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3284816896.0000 - mean_absolute_error: 49401.0352 - val_loss: 3312387328.0000 - val_mean_absolute_error: 49518.1719
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3284478208.0000 - mean_absolute_error: 49396.6914 - val_loss: 3311532800.0000 - val_mean_absolute_error: 49519.4141
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3284032256.0000 - mean_absolute_error: 49400.6914 - val_loss: 3311855872.0000 - val_mean_absolute_error: 49517.9805
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3283467520.0000 - mean_absolute_error: 49387.6914 - val_loss: 3312494080.0000 - val_mean_absolute_error: 49520.5117
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3283409664.0000 - mean_absolute_error: 49390.4805 - val_loss: 3312669696.0000 - val_mean_absolute_error: 49520.7812
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3283323904.0000 - mean_absolute_error: 49389.7539 - val_loss: 3312552192.0000 - val_mean_absolute_error: 49522.6641

In [89]:
## Evaluate the model
model.evaluate(X_test_scaled, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3355018496.0000 - mean_absolute_error: 50106.8242

[3355018496.0, 50106.82421875]

In [91]:
%load_ext tensorboard

In [93]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6009 (pid 20132), started 0:00:27 ago. (Use '!kill 20132' to kill it.)

In [94]:
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.