In [95]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [96]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [97]:
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [98]:
## encoding categorical variables
label_encoder = LabelEncoder()
data['Gender']= label_encoder.fit_transform(data['Gender'])

In [99]:
onehot_encoder = OneHotEncoder(sparse_output=False)

geo_encoded = onehot_encoder.fit_transform(data[['Geography']])

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder.get_feature_names_out(['Geography'])
)

geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [100]:
df=pd.concat([data, geo_encoded_df], axis=1).drop(['Geography'], axis=1)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [101]:
X=df.drop(['EstimatedSalary'], axis=1)
y=df['EstimatedSalary']

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [103]:
## make pickle files for the scaler and encoders
with open('scaler_salary.pkl', 'wb') as file:
    pickle.dump(scaler, file)

with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)    

with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot_encoder, file)

In [104]:
## ANN Regression Model
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),   
    Dense(1, activation='linear')
])  

## compile the model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mean_squared_error',
    metrics=['mean_absolute_error']
)

d:\Data Science\ANN_Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [105]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [106]:

import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [107]:
early_stopping = EarlyStopping(
    monitor='val_loss', 
    patience=10,
    restore_best_weights=True
)

In [ ]:
model.fit(
    X_train_scaled,
    y_train,
    validation_split=0.2,
    epochs=100,
    callbacks=[early_stopping, tensorboard_callback]
)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 13307904000.0000 - mean_absolute_error: 99976.8594 - val_loss: 13695188992.0000 - val_mean_absolute_error: 102024.9375
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13229045760.0000 - mean_absolute_error: 99584.8672 - val_loss: 13532449792.0000 - val_mean_absolute_error: 101230.1406
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12941126656.0000 - mean_absolute_error: 98145.5781 - val_loss: 13095056384.0000 - val_mean_absolute_error: 99096.6172
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 12336764928.0000 - mean_absolute_error: 95149.1094 - val_loss: 12306725888.0000 - val_mean_absolute_error: 95230.9531
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11381117952.0000 - mean_absolute_error: 90402.5938 - val_loss: 11171140608.0000 - val_mean_absolute_error: 89643.3203
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10122530816.0000 - mean_absolute_error: 84124.2188 - val_loss: 9777162240.0000 - val_mean_absolute_error: 82701.5234
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8681452544.0000 - mean_absolute_error: 76875.3281 - val_loss: 8270210048.0000 - val_mean_absolute_error: 75110.3359
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7227728384.0000 - mean_absolute_error: 69588.2812 - val_loss: 6829570048.0000 - val_mean_absolute_error: 67802.9375
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5934815744.0000 - mean_absolute_error: 62984.0469 - val_loss: 5618638336.0000 - val_mean_absolute_error: 61545.6016
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 4930551808.0000 - mean_absolute_error: 57832.9688 - val_loss: 4720113664.0000 - val_mean_absolute_error: 56750.8750
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4252113664.0000 - mean_absolute_error: 54324.8398 - val_loss: 4145264640.0000 - val_mean_absolute_error: 53637.7383
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 3853224960.0000 - mean_absolute_error: 52313.9219 - val_loss: 3814796288.0000 - val_mean_absolute_error: 51935.1211
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3641495808.0000 - mean_absolute_error: 51230.7695 - val_loss: 3636845568.0000 - val_mean_absolute_error: 50996.7539
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3537114624.0000 - mean_absolute_error: 50728.4883 - val_loss: 3543494144.0000 - val_mean_absolute_error: 50493.4414
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3484106496.0000 - mean_absolute_error: 50502.0352 - val_loss: 3491808256.0000 - val_mean_absolute_error: 50209.2969
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3453732096.0000 - mean_absolute_error: 50366.8711 - val_loss: 3461018624.0000 - val_mean_absolute_error: 50049.2188
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3433309440.0000 - mean_absolute_error: 50265.9258 - val_loss: 3439039488.0000 - val_mean_absolute_error: 49948.6406
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3417729024.0000 - mean_absolute_error: 50190.9688 - val_loss: 3422975488.0000 - val_mean_absolute_error: 49873.9648
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3405691392.0000 - mean_absolute_error: 50130.0391 - val_loss: 3411334656.0000 - val_mean_absolute_error: 49827.1758
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3395577344.0000 - mean_absolute_error: 50079.4492 - val_loss: 3402555648.0000 - val_mean_absolute_error: 49795.0586
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3386966016.0000 - mean_absolute_error: 50028.1836 - val_loss: 3393526272.0000 - val_mean_absolute_error: 49757.7305
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3379014656.0000 - mean_absolute_error: 49990.7148 - val_loss: 3386494720.0000 - val_mean_absolute_error: 49731.3711
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3372470016.0000 - mean_absolute_error: 49954.3438 - val_loss: 3379661312.0000 - val_mean_absolute_error: 49707.7617
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3366580992.0000 - mean_absolute_error: 49927.2344 - val_loss: 3375774208.0000 - val_mean_absolute_error: 49695.0547
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3361267456.0000 - mean_absolute_error: 49897.8164 - val_loss: 3370062336.0000 - val_mean_absolute_error: 49672.9219
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3356251904.0000 - mean_absolute_error: 49866.6602 - val_loss: 3366227456.0000 - val_mean_absolute_error: 49658.6836
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3352217088.0000 - mean_absolute_error: 49846.0508 - val_loss: 3361652992.0000 - val_mean_absolute_error: 49643.6133
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 3348042752.0000 - mean_absolute_error: 49821.6367 - val_loss: 3357394944.0000 - val_mean_absolute_error: 49629.9414
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3344435200.0000 - mean_absolute_error: 49805.2305 - val_loss: 3354915072.0000 - val_mean_absolute_error: 49624.3594
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3341096704.0000 - mean_absolute_error: 49779.4883 - val_loss: 3352757760.0000 - val_mean_absolute_error: 49617.5742
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3337968384.0000 - mean_absolute_error: 49766.1094 - val_loss: 3349885440.0000 - val_mean_absolute_error: 49612.0234
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3335170560.0000 - mean_absolute_error: 49746.2305 - val_loss: 3347536896.0000 - val_mean_absolute_error: 49606.1953
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3333094656.0000 - mean_absolute_error: 49734.0547 - val_loss: 3346377216.0000 - val_mean_absolute_error: 49604.2891
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3330016000.0000 - mean_absolute_error: 49717.8867 - val_loss: 3342572032.0000 - val_mean_absolute_error: 49593.9336
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3327675392.0000 - mean_absolute_error: 49706.4688 - val_loss: 3341665280.0000 - val_mean_absolute_error: 49592.9102
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3325777408.0000 - mean_absolute_error: 49690.9883 - val_loss: 3340476160.0000 - val_mean_absolute_error: 49588.4453
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3323873536.0000 - mean_absolute_error: 49678.6445 - val_loss: 3338181888.0000 - val_mean_absolute_error: 49583.8789
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3321867520.0000 - mean_absolute_error: 49671.1445 - val_loss: 3337242624.0000 - val_mean_absolute_error: 49580.1094
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3320735744.0000 - mean_absolute_error: 49665.3633 - val_loss: 3336002560.0000 - val_mean_absolute_error: 49577.0000
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3319008512.0000 - mean_absolute_error: 49653.3516 - val_loss: 3334381312.0000 - val_mean_absolute_error: 49574.2266
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3317446656.0000 - mean_absolute_error: 49643.6289 - val_loss: 3333910272.0000 - val_mean_absolute_error: 49571.5156
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 3316292608.0000 - mean_absolute_error: 49636.6641 - val_loss: 3331597568.0000 - val_mean_absolute_error: 49567.3555
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 3314728192.0000 - mean_absolute_error: 49626.3594 - val_loss: 3332182784.0000 - val_mean_absolute_error: 49568.7266
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 3313708032.0000 - mean_absolute_error: 49616.4062 - val_loss: 3331778048.0000 - val_mean_absolute_error: 49568.8711
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 3311925248.0000 - mean_absolute_error: 49612.0547 - val_loss: 3330330880.0000 - val_mean_absolute_error: 49565.5234
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3311280128.0000 - mean_absolute_error: 49603.1641 - val_loss: 3330313216.0000 - val_mean_absolute_error: 49565.6758
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 3309998592.0000 - mean_absolute_error: 49597.8711 - val_loss: 3330021888.0000 - val_mean_absolute_error: 49564.6016
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 3309012992.0000 - mean_absolute_error: 49588.3984 - val_loss: 3327767040.0000 - val_mean_absolute_error: 49558.9688
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 3308112384.0000 - mean_absolute_error: 49583.5195 - val_loss: 3327470080.0000 - val_mean_absolute_error: 49558.6484
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 3307298560.0000 - mean_absolute_error: 49577.0586 - val_loss: 3326421248.0000 - val_mean_absolute_error: 49555.2383
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3306376704.0000 - mean_absolute_error: 49569.3867 - val_loss: 3326528000.0000 - val_mean_absolute_error: 49554.5117
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3305525504.0000 - mean_absolute_error: 49560.5742 - val_loss: 3326953984.0000 - val_mean_absolute_error: 49557.1602
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3304606720.0000 - mean_absolute_error: 49558.3359 - val_loss: 3325865472.0000 - val_mean_absolute_error: 49554.8086
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3303828480.0000 - mean_absolute_error: 49549.6562 - val_loss: 3324775424.0000 - val_mean_absolute_error: 49553.1719
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3303153920.0000 - mean_absolute_error: 49546.1406 - val_loss: 3324068096.0000 - val_mean_absolute_error: 49551.1289
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3302765312.0000 - mean_absolute_error: 49547.1719 - val_loss: 3325307136.0000 - val_mean_absolute_error: 49553.2500
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3301933824.0000 - mean_absolute_error: 49536.3281 - val_loss: 3325296384.0000 - val_mean_absolute_error: 49555.2188
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3301047040.0000 - mean_absolute_error: 49532.4336 - val_loss: 3325585408.0000 - val_mean_absolute_error: 49555.6992
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 3300399872.0000 - mean_absolute_error: 49522.2109 - val_loss: 3324325120.0000 - val_mean_absolute_error: 49552.9219
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3299957248.0000 - mean_absolute_error: 49523.1992 - val_loss: 3323828736.0000 - val_mean_absolute_error: 49551.6133
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3299241472.0000 - mean_absolute_error: 49521.6055 - val_loss: 3323754496.0000 - val_mean_absolute_error: 49552.5742
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 3298593024.0000 - mean_absolute_error: 49512.3164 - val_loss: 3322623744.0000 - val_mean_absolute_error: 49548.5703
Epoch 63/100

In [ ]:
## Evaluate the model
model.evaluate(X_test_scaled, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3355018496.0000 - mean_absolute_error: 50106.8242

[3355018496.0, 50106.82421875]

In [ ]:
%load_ext tensorboard

In [ ]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6009 (pid 20132), started 0:00:27 ago. (Use '!kill 20132' to kill it.)

In [ ]:
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.